**Introduction to Data Wrangling**

Description: This lab covers two main concepts: 1) the basic concept of NumPy and Pandas; 2) reading files from various data sources. You may use Spyder or Jupyter Notebook to complete the tasks.

**Part 1: Pandas and NumPy**

Task 1: Pandas Series 
Create Pandas Series from lists. Run the following code and observe the output.

In [3]:
#import the modules for pandas and numpy

import pandas as pd
import numpy as np

# create two lists
emp_name_list = ["Alice", "Bob", "Cathy"]
emp_height_list = [168, 170, 155]

# create series from lists
emp_name_series = pd.Series(emp_name_list, name="Employee_Name")
emp_height_series = pd.Series(emp_height_list, name="Employee_Height")

print("\nPrint Series")
print(emp_name_series, "\n")
print(emp_height_series)

print("\nAccess a particular element using index")
print(emp_name_series[1])
print(emp_height_series[1])




Print Series
0    Alice
1      Bob
2    Cathy
Name: Employee_Name, dtype: object 

0    168
1    170
2    155
Name: Employee_Height, dtype: int64

Access a particular element using index
Bob
170


**Task 2: Pandas DataFrame**

Create a Pandas DataFrame. Run the following code and observe the output. Discuss the difference between Series and DataFrame.


In [4]:
import pandas as pd
import numpy as np

# create a dictionary
emp_profile = {"Name": emp_name_series, "Height": emp_height_series}

# create a dataframe from dictionary
emp_df = pd.DataFrame(emp_profile)

print("\nPrint dataframe")
print(emp_df)

print("\nSelect a column")
print(emp_df['Name'])

print("\nSelect multiple columns")
print(emp_df[['Name','Height']])

print("\nSelect a row")
print(emp_df.iloc[2])

print("\nSelect multiple rows")
print(emp_df.iloc[[1, 2]])

print("\nOther examples")
print(emp_df["Name"][0])
print(emp_df["Height"][1])

#Sample solution: Series is a one-dimensional array whereas DataFrame consists of rows and columns. 


Print dataframe
    Name  Height
0  Alice     168
1    Bob     170
2  Cathy     155

Select a column
0    Alice
1      Bob
2    Cathy
Name: Name, dtype: object

Select multiple columns
    Name  Height
0  Alice     168
1    Bob     170
2  Cathy     155

Select a row
Name      Cathy
Height      155
Name: 2, dtype: object

Select multiple rows
    Name  Height
1    Bob     170
2  Cathy     155

Other examples
Alice
170


**Challenging Task 3: Pandas DataFrame (Explicit Indexing)**

Modify the code in Task 2 to explicitly provide an index to the dataframe emp_df as shown below. 
What did you observe? How to fix the issue (if any)?

In [5]:
import pandas as pd
import numpy as np

# create a dictionary
emp_profile = {"Name": emp_name_series, "Height": emp_height_series}

# create a dataframe from dictionary
# emp_df = pd.DataFrame(emp_profile)

# create a dataframe from dictionary
emp_df = pd.DataFrame(emp_profile, index=['1001', '1002', '1003'])


print("\nPrint dataframe")
print(emp_df)
print()

# create series from lists
emp_name_series = pd.Series(emp_name_list, name="Employee_Name", index=['1001', '1002', '1003'])
emp_height_series = pd.Series(emp_height_list, name="Employee_Height", index=['1001', '1002', '1003'])

#print(emp_df['Name'])

# create a dictionary
emp_profile = {"Name": emp_name_series, "Height": emp_height_series}

# create a dataframe from dictionary
emp_df = pd.DataFrame(emp_profile, index=['1001', '1002', '1003'])

print("\nPrint dataframe")
print(emp_df)




Print dataframe
     Name  Height
1001  NaN     NaN
1002  NaN     NaN
1003  NaN     NaN


Print dataframe
       Name  Height
1001  Alice     168
1002    Bob     170
1003  Cathy     155


**Task 4: NumPy vs Python List**

Run the following code and observe the difference in the loop execution time between Python list and NumPy. Which structure is faster? 


In [6]:
import pandas as pd
import numpy as np
import time

size_vec = 2000000
t1 = time.time()
X = range(size_vec)
Y = range(size_vec)
Z = [X[i]+Y[i] for i in range(len(X))]
list_time = time.time()-t1

t2 = time.time()
X2 = np.arange(size_vec)
Y2 = np.arange(size_vec)
Z2 = X2+Y2
list_time2 = time.time()-t2

print(list_time, list_time2)

#Numpy is faster than list

0.8538024425506592 0.009830951690673828


**Task 5: NumPy Array within Specified Range**

1) Create a NumPy array by using the arange() function to produce elements between 5 – 20. The difference between two elements is 5. The elements of array: 5, 10, 15. Run and study the following code. 

2) Create a NumPy array by using the arange() function to produce elements between 11 – 17. The difference between two elements is 2. Then, add this array with 5. The elements of the array after the addition are: 16, 18, 20. Print the array elements.

[Further reading: https://numpy.org/doc/stable/reference/generated/numpy.arange.html]



In [5]:
import pandas as pd
import numpy as np

print("Question 1")
# 5 to 20, step: 5
array1= np.arange(5,20,5)
print(array1)
print()

print("Question 2")

array1= np.arange(11,17,2) + 5
print(array1)
print()

Question 1
[ 5 10 15]

Question 2
[16 18 20]



**Task 6: One-dimensional (1D) NumPy Array**

1) Create a 1D NumPy array with five elements using the array() function. Run the following code.
2) Calculate and print the mean and standard deviation of the array.
3) [Challenging task] Format the output as follows:

Sample output: The mean is X and standard deviation is Y. (X and Y represent the mean and standard deviation respectively)


In [13]:
import pandas as pd
import numpy as np

print("Question 1")
my_array = np.array([30,22,18,10,20])
print("1D array: ", my_array)
print()

print("Question 2")
m = np.mean(my_array)
std = np.std(my_array)

print("Mean :", m)
print("Standard Deviation :", std)

print()
print("Question 3")
print(f"The mean is {x} and standard deviation is {y}.")
print("The mean is %f and standard deviation is %f." %(m, std))

Question 1
1D array:  [30 22 18 10 20]

Question 2
Mean : 20.0
Standard Deviation : 6.44980619863884

Question 3
The mean is 20.0 and standard deviation is 6.44980619863884.
The mean is 20.000000 and standard deviation is 6.449806.


**Challenging Task 7: 1D NumPy Array and User Input**

Let the user input the total number of elements of a 1D NumPy array. Create the array and use a for loop to let the user input each element into the array. Finally, print every element of the array. 

Sample output: 
Please enter the total number of array elements: 5
Enter an element: 9
Enter an element: 8
Enter an element: 6
Enter an element: 3
Enter an element: 2
[9 8 6 3 2]


In [24]:
num = int(input("Please enter the total number of array elements: "))

arr1 = []

for x in range(num):
    element = input("Enter an element: ")
    #  add number to the array
    arr1.append(element)
arr2 = np.array(arr1)

# print array
print(arr2)
    

Please enter the total number of array elements:  3
Enter an element:  5
Enter an element:  6
Enter an element:  3


['5' '6' '3']


**Task 8: Two-dimensional (2D) NumPy Array**

Create a 2D NumPy array with six elements (2 rows and 3 columns) using the array() function. Run the following code.

In [13]:
import pandas as pd
import numpy as np

my_array2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", my_array2)


2D array:
 [[1 2 3]
 [4 5 6]]


**Challenging Task 9: 2D NumPy Array and User Input**

Create a 2D NumPy array with the size of 3 * 5. Let the user input each element into the array. Then, compute the mean for each row. 

You may test your program with the following values: 

[3 8 2 9 2

 7 5 8 9 9
 
 6 4 3 2 7]
 
The mean values of the rows are 4.8, 7.6, and 4.4 respectively.

In [33]:
matrix = []
for x in range(3):
    a = []
    for y in range(5):  
        # get user input
        element = int(input("Enter a number: "))
        # append value to array
        a.append(element)
    matrix.append(a)
    
my_arr = np.array(matrix)
print(my_arr)
print(np.mean(my_arr, axis=1))
# print(f"The mean values of the rows are {m}, {m}, and {m} respectively.")

Enter a number:  3
Enter a number:  8
Enter a number:  2
Enter a number:  9
Enter a number:  2
Enter a number:  7
Enter a number:  5
Enter a number:  8
Enter a number:  9
Enter a number:  9
Enter a number:  6
Enter a number:  4
Enter a number:  3
Enter a number:  2
Enter a number:  7


[[3 8 2 9 2]
 [7 5 8 9 9]
 [6 4 3 2 7]]
[4.8 7.6 4.4]


**Part 2: Reading Data**

Task 10: Read XML
Read an XML file (download student.xml from Google Classroom) using Pandas and print all the data. Run and study the following code.


In [18]:
!pip install pandas-read-xml

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import pandas_read_xml as pdx
import numpy as np

student_df = pdx.read_xml("student.xml")
print(student_df)


                                          University
0  {'Student': [{'Name': 'Alice', 'ID': '123456',...


**Task 11: Read JSON**

Read a JSON file from https://data.covid19india.org/state_district_wise.json using Pandas and extract the number of active cases in South Andaman. Run and study the following code.

In [9]:
import pandas as pd

df = pd.read_json('https://api.covid19india.org/state_district_wise.json')

active_case = df['Andaman and Nicobar Islands']['districtData']['South Andaman']['active']
print("Active cases in South Andaman:", active_case)



Active cases in South Andaman: 19


**Task 12: Read CSV**

You can refer to Examples 26 to 28 in Lab 1 Part 2 to complete the exercise below.

**Task 13: Read Data using read_table()**
Read the data from UCI Machine Learning Repository at https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data into a dataframe. [Hint: You may consider using the read_table() function. Identify the delimiter used in the data file. Print the data using the head() function of the dataframe.]


In [38]:
import pandas as pd 
data_bc = pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data",
                        delimiter=',')          
data_bc

,1000025,5,1,1.1,1.2,2,1.3,3,1.4,1.5,2.1
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4


References: 
https://www.geeksforgeeks.org/getting-started-with-python-programming/?ref=shm
https://medium.com/@nishantbhushan10/python-lists-tuples-sets-dictionary-a9cbcac183e3
https://hackr.io/blog/python-data-structures
